# Generated by Django 4.1.6 on 2023-02-06 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='Token',
            new_name='token',
        ),
        migrations.AddField(
            model_name='cart',
            name='status',
            field=models.CharField(choices=[('not_checked_out', 'Yet to Check Out'), ('checked_out', 'Has Checked Out')], default='checked_out', max_length=100),
        ),
        migrations.AlterField(
            model_name='userreview',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.DeleteModel(
            name='Checkout',
        ),
    ]
