# Generated by Django 4.1.6 on 2023-02-06 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_rename_token_coupon_token_cart_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='alt_phone',
        ),
        migrations.RemoveField(
            model_name='address',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='address',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='address',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='address',
            name='status',
        ),
        migrations.RemoveField(
            model_name='pickupstation',
            name='additional_info',
        ),
        migrations.RemoveField(
            model_name='pickupstation',
            name='address',
        ),
        migrations.RemoveField(
            model_name='pickupstation',
            name='city',
        ),
        migrations.RemoveField(
            model_name='pickupstation',
            name='state',
        ),
        migrations.AddField(
            model_name='pickupstation',
            name='address_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pickup_stations', to='backend.address'),
        ),
        migrations.AddField(
            model_name='pickupstation',
            name='name',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='alt_phone',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='first_name',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='last_name',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='phone',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Cancelled')], default='active', max_length=100),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='type',
            field=models.CharField(choices=[('user_address', 'User Address'), ('pickup_address', 'Pickup Station Address')], default='user_address', max_length=100),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='region_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='backend.region'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='name',
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='name',
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='region',
            name='state',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
