# Generated by Django 4.1.6 on 2023-02-06 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_remove_address_alt_phone_remove_address_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickupstation',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
